# Makefile template file for FLAME
#
# FLAME is the FLAME source files
# SOURCE is the user source files
#
# The assumption is that the user only provides C files
# and a model files <file>.xml
#
#===================================================
# Change this variable for the location of the 
# Message Board Library installation
#===================================================
LIBMBOARD_DIR = /usr/local
LIBMBOARD_INC = $(LIBMBOARD_DIR)/include
LIBMBOARD_LIB = $(LIBMBOARD_DIR)/lib

#====================================================
# Change these for your compliler/loaded
#====================================================
SERIAL_CCOMP	= gcc
PARALLEL_CCOMP	= mpicc

SERIAL_LOADER	= gcc
PARALLEL_LOADER	= mpif77

DEFINES		=
<?if gsl_lib?>
#DEFINE for using GSL_LIB
DEFINES		+= -DGSL_LIB
<?end if?>

# C Compiler
CC      = <?if serial?>$(SERIAL_CCOMP)<?end if?><?if parallel?>$(PARALLEL_CCOMP)<?end if?>
CFLAGS  =  -I$(LIBMBOARD_INC) ${DEFINES}
<?if debug?>CFLAGS += -std=c99 -Wall -D_DEBUG_MODE -g<?end if?>
<?if final?>CFLAGS += -O3<?end if?>

# Executable builder
LD       = <?if serial?>$(SERIAL_LOADER)<?end if?><?if parallel?>$(PARALLEL_LOADER)<?end if?>
LDFLAGS  = -L$(LIBMBOARD_LIB)

#Libraries to scan
LIBS =
<?if gsl_lib?>
#GSL Libraries
LIBS	+= -lgsl -lgslcblas
<?end if?>
# Message board library
LIBS    += <?if serial?>-lmboard_s<?if debug?>d<?end if?> <?end if?><?if parallel?>-lmboard_p<?if debug?>d<?end if?> <?end if?> -lm

#FLAME source files
FLAME   = main.c memory.c xml.c messageboards.c partitioning.c rules.c timing.c

#FLAME auxilary files
AUX 	= stategraph.dot stategraph_colour.dot process_order_graph.dot Doxyfile latex.tex

#include $(FLAME_XPARSER_DIR)/cg.mk

# FLAME generated model files
SOURCES = <?foreach functionfiles?> $filepath <?end foreach?>
HEADERS = header.h low_primes.h mboard.h <?foreach xagent?> $name_agent_header.h <?end foreach?>

DEPS    = Makefile header.h low_primes.h

OBJECTS = $(SOURCES:.c=.o) $(FLAME:.c=.o)
EXECUTABLE = main
RM = rm -f

all: $(SOURCES) $(FLAME) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(LD) $(LDFLAGS) $(OBJECTS) -o $@ $(LIBS)

$(OBJECTS): $(DEPS)

.c.o:
	$(CC) -c $(CFLAGS) $< -o $@

clean:
	$(RM) $(OBJECTS) $(EXECUTABLE) $(EXECUTABLE).exe 
vclean:
	$(RM) main $(EXECUTABLE) $(EXECUTABLE).exe $(OBJECTS)  $(FLAME) $(HEADERS)  $(AUX) Makefile
format:
	astyle -A3 $(SOURCES)
	for file in $(patsubst %.c,%.h, $(SOURCES)) ; do \
	echo $$file ; \
	astyle -A3 $$file ; \
	done 
print:
	a2ps -R -f10 --column=1 $(SOURCES)
